import { createSlice } from '@reduxjs/toolkit';

const initialState = [
   {
      id: 1,
      category: 1,
      trending: 'today',
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 299,
   },
   {
      id: 2,
      category: 1,
      trending: 'today',
      name: 'Sunset Acai Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/sunset-acai.png',
      price: 159,
   },
   {
      id: 3,
      category: 1,
      trending: 'today',
      name: 'Blueberry Avac Smoothie Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/blueberry.png',
      price: 199,
   },
   {
      id: 4,
      category: 1,
      trending: 'today',
      name: 'Johnnie Walker Blue Label (1L)',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/bluelabel.png',
      price: 1099,
   },
   {
      id: 5,
      category: 1,
      trending: 'today',
      name: 'Green Goddess',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/sunrise-acai.png',
      price: 219,
   },
   {
      id: 6,
      category: 1,
      trending: 'today',
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 399,
   },
   {
      id: 7,
      category: 1,
      trending: 'week',
      tags: ['VEGAN', 'GLUTEN-FREE'],
      name: 'Blueberry Avac Smoothie Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/blueberry.png',
      price: 199,
   },
   {
      id: 8,
      category: 3,
      subCategory: 5,
      name: 'Tofu Scramble (VEGAN)',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/bluelabel.png',
      price: 310,
   },
   {
      id: 9,
      category: 3,
      subCategory: 5,
      name: 'Nut-buster Acai (VEGAN)',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/tempus.png',
      price: 480,
   },
   {
      id: 10,
      category: 3,
      subCategory: 6,
      name: 'Turmeric Lemonade',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/blueberry.png',
      price: 210,
   },
   {
      id: 11,
      category: 3,
      subCategory: 6,
      name: 'Think Coconut',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 130,
   },
   {
      id: 12,
      category: 4,
      subCategory: 3,
      name: 'Sacred Earth Latte',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/sunset-acai.png',
      price: 190,
   },
   {
      id: 13,
      category: 4,
      subCategory: 3,
      name: 'Black Coffee Freddo',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/sunrise-acai.png',
      price: 170,
   },
   {
      id: 14,
      category: 4,
      subCategory: 4,
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 439,
   },
   {
      id: 15,
      category: 4,
      subCategory: 4,
      name: 'Turmeric Brew Latte',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/blueberry.png',
      price: 219,
   },
   {
      id: 16,
      category: 5,
      subCategory: 1,
      name: 'Sandwich Loaf',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/tempus.png',
      price: 120,
   },
   {
      id: 17,
      category: 5,
      subCategory: 1,
      name: 'Pesto Croissant',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/bluelabel.png',
      price: 220,
   },
   {
      id: 18,
      category: 5,
      subCategory: 2,
      name: 'Gunpowder Fish Cakes',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/blueberry.png',
      price: 450,
   },
   {
      id: 19,
      category: 5,
      subCategory: 2,
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 399,
   },
];

export default createSlice({
   name: 'foods',
   initialState,
}).reducer;
