import { createSlice } from '@reduxjs/toolkit';

const initialState = [
   {
      id: 1,
      category: 1,
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 299,
   },
   {
      id: 2,
      category: 1,
      name: 'Sunset Acai Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/sunset-acai.png',
      price: 159,
   },
   {
      id: 3,
      category: 1,
      name: 'Blueberry Avac Smoothie Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/blueberry.png',
      price: 199,
   },
   {
      id: 4,
      category: 1,
      name: 'Johnnie Walker Blue Label (1L)',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/bluelabel.png',
      price: 1099,
   },
   {
      id: 5,
      category: 1,
      name: 'Green Goddess',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/sunrise-acai.png',
      price: 219,
   },
   {
      id: 6,
      category: 1,
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 399,
   },
   {
      id: 7,
      category: 3,
      subCategory: 5,
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 399,
   },
   {
      id: 8,
      category: 3,
      subCategory: 5,
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 399,
   },
   {
      id: 9,
      category: 3,
      subCategory: 6,
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 399,
   },
   {
      id: 10,
      category: 3,
      subCategory: 6,
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 399,
   },
   {
      id: 11,
      category: 4,
      subCategory: 3,
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 399,
   },
   {
      id: 12,
      category: 4,
      subCategory: 3,
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 399,
   },
   {
      id: 13,
      category: 4,
      subCategory: 4,
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 399,
   },
   {
      id: 14,
      category: 4,
      subCategory: 4,
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 399,
   },
   {
      id: 15,
      category: 5,
      subCategory: 1,
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 399,
   },
   {
      id: 16,
      category: 5,
      subCategory: 1,
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 399,
   },
   {
      id: 17,
      category: 5,
      subCategory: 2,
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 399,
   },
   {
      id: 18,
      category: 5,
      subCategory: 2,
      name: 'Chocolate Bowl',
      image: 'https://raw.githubusercontent.com/pmfoysal/data/main/sacred-earth-cafe/chocolate.png',
      price: 399,
   },
];

export default createSlice({
   name: 'foods',
   initialState,
}).reducer;
